# SPDX-FileCopyrightText: 2017 Jussi Pakkanen
#
# SPDX-License-Identifier: CC0-1.0

image: Visual Studio 2019

environment:
  matrix:
    - arch: x86
      compiler: msvc2019
    - arch: x64
      compiler: msvc2019
  api_token:
    secure: ED4kqXSHe32rlVYnkZdP4mWu+/UHWp0/DmKiQvhvzavp4vtbzcSHiYp/HEtEK3VL
  zone_id:
    secure: ds1KfFqFjuCHJg7jdGVwFON4Ys0z029hkqyUE6h7J/1+tECQzLTxHkGBpl4S30Ud
  record_name:
    secure: IiQA4wuz76kwEqZ+K+bB7v/obAtUJnt7xvdebkPMvrz76VsxGvrYGDTZQYBzq3xs

platform:
  - x64

install:
  # Set paths to dependencies (based on architecture)
  - cmd: if %arch%==x86 (set PYTHON_ROOT=C:\Python39) else (set PYTHON_ROOT=C:\Python39-x64)
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install meson and ninja
  - cmd: pip install --quiet ninja meson==0.59.4
  # Set up the build environment
  - cmd: if %compiler%==msvc2019 ( call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )

build_script:
  - cmd: meson setup build --default-library=static -Db_vscrt=static_from_buildtype -Dtests=true -Dtest_api_token=%api_token% -Dtest_zone_id=%zone_id% -Dtest_record_name=%record_name%
  - cmd: meson compile -C build

test_script:
  - cmd: meson test -C build --verbose

artifacts:
  - path: build\cloudflare-ddns.exe
    name: cloudflare-ddns-x64
