# SPDX-FileCopyrightText: 2017 Jussi Pakkanen
#
# SPDX-License-Identifier: CC0-1.0

image: Visual Studio 2019

environment:
  matrix:
    #    - arch: x86
    #      compiler: msvc2019
    - arch: x64
      compiler: msvc2019
  api_token:
    secure: Zo4CXhD9M2XoeZkF1emEcQK/g6PGIFztGZ1FaYaKg7I5YhDbj962xzj0jqUhgW2C
  zone_id:
    secure: SQDa4GZsqrxoVemMabChKXvSOt+EM1Ky2EX6dyN0w7zitwTsQeYOEh8gFMkA21in
  record_name:
    secure: EElzS3TkDp8Ph6oz3DWAQxtcbuQE9nyxhjlbEgqcOn4=

platform:
  - x64

install:
  # Set paths to dependencies (based on architecture)
  - cmd: if %arch%==x86 (set PYTHON_ROOT=C:\Python39) else (set PYTHON_ROOT=C:\Python39-x64)
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install meson and ninja
  - cmd: pip install --quiet ninja meson
  # Set up the build environment
  - cmd: if %compiler%==msvc2019 ( call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )

build_script:
  - cmd: meson setup build --default-library=static --buildtype=debugoptimized -Db_vscrt=static_from_buildtype -Db_sanitize=address -Dtests=true -Dtest_api_token=%api_token% -Dtest_zone_id=%zone_id% -Dtest_record_name=%arch%.%record_name%
  - cmd: meson compile -C build --verbose

test_script:
  - cmd: meson test -C build --verbose

artifacts:
  - path: build\exe\cloudflare-ddns.exe
    name: cloudflare-ddns-x64
