# SPDX-FileCopyrightText: 2017 Jussi Pakkanen
#
# SPDX-License-Identifier: CC0-1.0

image: Visual Studio 2019

environment:
  matrix:
    - arch: x86
      compiler: msvc2019
    - arch: x64
      compiler: msvc2019
  api_token:
    secure: FYndh51cRZ1KxFHtQhii7eDzx0OYeW0dHT82bl972BZD1bFFN6P11+lbqig6G+1e
  zone_id:
    secure: flt5oxYUyOPQFy0k6V7WamNY7M+FPN6Yqdpoq6+IJffKiFQzN+tZdqKkjFTKzbzC
  record_name:
    secure: 7JMS5OhFLPMgdlRoE8LgPJ64MTaZQkIASB2FOX9cCc8+pcGaxaCgFHGzGp/765jq

platform:
  - x64

install:
  # Set paths to dependencies (based on architecture)
  - cmd: if %arch%==x86 (set PYTHON_ROOT=C:\Python39) else (set PYTHON_ROOT=C:\Python39-x64)
  # Add necessary paths to PATH variable
  - cmd: set PATH=%cd%;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Install meson and ninja
  - cmd: pip install --quiet ninja meson==0.59.3
  # Set up the build environment
  - cmd: if %compiler%==msvc2019 ( call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )

build_script:
  - cmd: meson setup build --default-library=static -Db_vscrt=static_from_buildtype -Dtests=true -Dtest_api_token=$Env:api_token -Dtest_zone_id=$Env:zone_id -Dtest_record_name=$Env:record_name
  - cmd: meson compile -C build

test_script:
  - cmd: meson test -C build --verbose

artifacts:
  - path: build\cloudflare-ddns.exe
    name: cloudflare-ddns-x64
