# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
#
# SPDX-License-Identifier: AGPL-3.0-or-later

path_classifiers:
  library:
  - subprojects
extraction:
  cpp:
    prepare:
      packages:
      - libcurl4-openssl-dev
      - libsimdjson-dev
      - curl
    after_prepare:
    - curl --silent --location --remote-name https://github.com/mesonbuild/meson/releases/download/0.59.1/meson-0.59.1.tar.gz
    - tar xf meson-0.59.1.tar.gz
    configure:
      command:
      - ./meson-0.59.1/meson.py setup build --buildtype=release
    index:
      build_command:
      - ./meson-0.59.1/meson.py compile -C build
