# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
#
# SPDX-License-Identifier: AGPL-3.0-or-later

path_classifiers:
  library:
  - subprojects
extraction:
  cpp:
    prepare:
      packages:
      - libcurl4-openssl-dev
      - libsimdjson-dev
      - curl
    after_prepare:
    - curl --silent --location --remote-name-all --proto '=https' https://github.com/mesonbuild/meson/releases/download/0.59.4/meson-0.59.4.tar.gz https://github.com/Kitware/CMake/releases/download/v3.21.4/cmake-3.21.4-linux-x86_64.tar.gz
    - tar xf meson-0.59.4.tar.gz
    - tar xf cmake-3.21.4-linux-x86_64.tar.gz

    configure:
      command:
      - PATH=$(pwd)/cmake-3.21.4-linux-x86_64/bin:$PATH ./meson-0.59.4/meson.py setup build -Dtests=true
    index:
      build_command:
      - ./meson-0.59.4/meson.py compile -C build
