name: CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list /etc/apt/sources.list.d/*
        printf "Enabled: yes\nTypes: deb\nURIs: http://azure.archive.ubuntu.com/ubuntu/\nSuites: focal focal-updates focal-backports focal-security\nComponents: main universe\n" | sudo tee /etc/apt/sources.list.d/system.sources
        sudo apt-get -qq update && sudo apt-get -qq install --assume-yes cmake libssl-dev

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest -C build

    - name: Store compiled program
      uses: actions/upload-artifact@v2
      with: 
        name: cloudflare-ddns-static-main
        path: ${{runner.workspace}}/cloudflare-ddns/build/cloudflare-ddns
