# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: linux

on: push

defaults:
  run:
    shell: sh

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    strategy:
      fail-fast: false
      # memsan is disabled because of https://github.com/openssl/openssl/issues/11013
      matrix:
        os: [ 'debian:stable', 'debian:testing', 'redhat/ubi8:latest' ]
        compiler: [ 'gcc', 'clang' ]
        sanitizer: [ 'address', 'thread', 'undefined', 'memory', 'none' ]
        exclude:
          - os: 'redhat/ubi8:latest'
            sanitizer: 'address'
          - os: 'redhat/ubi8:latest'
            sanitizer: 'thread'
          - os: 'redhat/ubi8:latest'
            sanitizer: 'undefined'
          - os: 'redhat/ubi8:latest'
            sanitizer: 'memory'
          - compiler: 'gcc'
            sanitizer: 'memory'
          - sanitizer: 'memory'

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}

    steps:
    # llvm-dev is required because it contains LLVMgold.so in Debian 11
    - name: Install dependencies (Debian)
      if: contains(matrix.os, 'debian')
      run: |
        if [ ${{ matrix.compiler }} = gcc ]; then compiler=g++; else compiler=clang; fi
        apt -y update
        apt -y install $compiler meson pkg-config cmake libcurl4-openssl-dev libsimdjson-dev libinih-dev git ca-certificates curl gpg gpgv gpg-agent lcov llvm-dev --no-install-recommends

    - name: Install dependencies (Red Hat)
      if: contains(matrix.os, 'redhat')
      run: |
        if [ ${{ matrix.compiler }} = gcc ]; then compiler=gcc-c++; else compiler=clang; fi
        yum install -y $compiler pkgconf cmake libcurl-devel git python3 gnupg
        pip3 install meson ninja

    - uses: actions/checkout@v2
      with:
        submodules: true

    # LTO disabled because of https://github.com/mesonbuild/meson/issues/8371
    - name: Configure Meson
      run: |
        if expr ${{ matrix.os }} : ".*redhat" >/dev/null; then enable_tests=false; else enable_tests=true; fi
        record_name=$(printf '${{ matrix.sanitizer }}.${{ matrix.compiler }}.${{ matrix.os }}.${{ github.workflow }}.ci.${{ secrets.DOMAIN_NAME }}' | tr -dc '[:alnum:].')
        if [ ${{ matrix.compiler }} = gcc ]; then CXX=g++; else CXX=clang++; fi
        export CXX
        meson setup build -Dtests=$enable_tests -Dtest_api_token='${{ secrets.API_TOKEN }}' -Dtest_zone_id='${{ secrets.ZONE_ID }}' -Dtest_record_name="$record_name" --buildtype=debug -Db_coverage=true -Db_sanitize=${{ matrix.sanitizer }} -Db_lundef=false -Db_lto=false
      env:
        CC: ${{ matrix.compiler }}

    - name: Build
      run: ninja -C build

    - name: Test
      if: ${{ !contains(matrix.os, 'redhat') }}
      run: meson test -C build --verbose

    - name: Coverage
      if: ${{ !contains(matrix.os, 'redhat') }}
      run: |
        mkdir --parents $HOME/.local/bin
        if [ "${{ matrix.compiler }}" = 'clang' ]; then printf 'llvm-cov gcov "$@"' > $HOME/.local/bin/cov.sh; else printf 'gcov "$@"' > $HOME/.local/bin/cov.sh; fi && chmod +x $HOME/.local/bin/cov.sh
        lcov --capture --output-file coverage.info --directory . --gcov-tool $HOME/.local/bin/cov.sh --exclude '/usr/*' --exclude "${HOME}"'/.cache/*' --exclude '*/tests/*' --exclude '*/subprojects/*'
        lcov --list coverage.info
        curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
        curl --silent --remote-name https://uploader.codecov.io/latest/linux/codecov
        curl --silent --remote-name https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
        curl --silent --remote-name https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
        gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
        sha256sum --check codecov.SHA256SUM
        chmod +x codecov
        ./codecov

    - run: ls --color=always -lAh build/*

    - name: Store compiled program
      if: matrix.sanitizer == 'none'
      uses: actions/upload-artifact@v3
      with:
        name: cloudflare-ddns-linux
        path: |
          build/libcloudflare-ddns.so.*
          !build/libcloudflare-ddns.so.*.p
          build/src/cloudflare-ddns
