# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: linux

on: push

defaults:
  run:
    shell: sh

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'debian:stable', 'debian:testing', 'redhat/ubi8:latest' ]
        compiler: [ 'gcc', 'clang' ]

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}

    steps:
    - name: Install dependencies (Debian)
      if: contains(matrix.os, 'debian')
      run: |
        if [ ${{ matrix.compiler }} = gcc ]; then compiler=g++; else compiler=clang; fi
        apt-get -qq update
        apt-get -qq install $compiler meson pkgconf cmake libcurl4-openssl-dev libsimdjson-dev git

    - name: Install dependencies (Red Hat)
      if: contains(matrix.os, 'redhat')
      run: |
        if [ ${{ matrix.compiler }} = gcc ]; then compiler=gcc-c++; else compiler=clang; fi
        yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        yum install -y $compiler meson pkgconf cmake libcurl-devel git

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Configure Meson
      run: meson setup build -Dtests=true -Dtest_api_token='${{ secrets.API_TOKEN }}' -Dtest_zone_id='${{ secrets.ZONE_ID }}' -Dtest_record_name='${{ secrets.RECORD_NAME }}'

    - name: Build
      run: ninja -C build

    - name: Test
      run: meson test -C build --verbose

    - name: Store compiled program
      uses: actions/upload-artifact@v2
      with:
        name: cloudflare-ddns-linux
        path: build/cloudflare-ddns
