# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Linux

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list /etc/apt/sources.list.d/*
        printf "Enabled: yes\nTypes: deb\nURIs: http://azure.archive.ubuntu.com/ubuntu/\nSuites: focal focal-updates focal-backports focal-security hirsute\nComponents: main universe\n" | sudo tee /etc/apt/sources.list.d/system.sources
        printf "APT::Default-Release \"focal\";\n" | sudo tee /etc/apt/apt.conf.d/00default-release
        sudo apt-get -qq update && sudo apt-get -qq install meson libcurl4-openssl-dev libsimdjson-dev/hirsute

    - name: Configure Meson
      run: meson setup build --buildtype=release

    - name: Build
      run: ninja -C build

    - name: Test
      run: meson test -C build --no-stdsplit --print-errorlogs

    - name: Store compiled program
      uses: actions/upload-artifact@v2
      with:
        name: cloudflare-ddns-linux
        path: ${{runner.workspace}}/cloudflare-ddns/build/cloudflare-ddns
