# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: linux

on: push

defaults:
  run:
    shell: sh

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'debian:stable', 'debian:testing', 'ubuntu:latest', 'ubuntu:rolling' ]

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get -qq update && sudo apt-get -qq install meson libcurl4-openssl-dev libsimdjson-dev

    - name: Configure Meson
      run: meson setup build -Dtests=true -Dtest_api_token='${{ secrets.API_TOKEN }}' -Dtest_zone_id='${{ secrets.ZONE_ID }}' -Dtest_record_name='${{ secrets.RECORD_NAME }}'

    - name: Build
      run: ninja -C build

    - name: Test
      run: meson test -C build --verbose

    - name: Store compiled program
      uses: actions/upload-artifact@v2
      with:
        name: cloudflare-ddns-linux
        path: build/cloudflare-ddns
