name: Windows

on: [push]

# env:
#   Path: "C:/Program Files/Meson;C:/Program Files/Git/bin;C:/Program Files/CMake/bin;C:/ProgramData/Chocolatey/bin;C:/Windows/system32"

jobs:
  windows-msvc:
    name: Windows - MSVC
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Meson
      run: |
        Invoke-WebRequest -Uri https://github.com/mesonbuild/meson/releases/download/0.57.1/meson-0.57.1.1-64.msi -OutFile meson.msi
        msiexec /i meson.msi /passive /qn

    - name: Configure Meson
      run: |
        $env:Path += ";C:/Program Files/Meson"
        meson setup build --buildtype=release

    - name: Build
      run: |
        $env:Path += ";C:/Program Files/Meson"
        meson compile -C build

    - name: Test
      run: meson test -C build

    - name: Store compiled program
      uses: actions/upload-artifact@v2
      with:
        name: cloudflare-ddns-windows
        path: ${{runner.workspace}}/cloudflare-ddns/build/cloudflare-ddns

  windows-clang-cl:
    name: Windows - clang-cl
    runs-on: windows-latest
    env:
      CC: "C:/Program Files/LLVM/bin/clang.exe"
      CXX: "C:/Program Files/LLVM/bin/clang++.exe"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Clang
      run: |
        Invoke-WebRequest -Uri https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/LLVM-11.1.0-win64.exe -OutFile llvm.exe
        7z x llvm.exe -y -o"C:/Program Files/LLVM"

    - name: Install Meson
      run: |
        Invoke-WebRequest -Uri https://github.com/mesonbuild/meson/releases/download/0.57.1/meson-0.57.1.1-64.msi -OutFile meson.msi
        msiexec /i meson.msi /passive /qn

    - name: Configure Meson
      run: |
        $env:Path += ";C:/Program Files/Meson"
        meson setup build --buildtype=release

    - name: Build
      run: |
        $env:Path += ";C:/Program Files/Meson"
        meson compile -C build

    - name: Test
      run: |
        $env:Path += ";C:/Program Files/Meson"
        meson test -C build

    - name: Store compiled program
      uses: actions/upload-artifact@v2
      with:
        name: cloudflare-ddns-windows-clang
        path: ${{runner.workspace}}/cloudflare-ddns/build/cloudflare-ddns
